# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mvpapi:
    image: mvpapi
    build:
      context: .
      dockerfile: MvpApi/Dockerfile
    ports:
      - 5175:5175
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
